copyright: Erfan Zare Chavoshi-EasyDel
nav:
  - Home: index.md
  - AvailableModels: AvailableModels.md
  - Install: Install.md
  - EasyBIT: Bits.md
  - Etils:
      - Configs: etils-configs.md
      - Errors: etils-errors.md
      - Etils: etils-etils.md
  - Eval:
      - Lm Eval: eval-lm_eval.md
  - Examples:
      - DataProcessing: DataProcessing.md
      - Falcon Models: Falcon.md
      - JAXServer: JAXServer.md
      - Llama Models: Llama.md
      - Llama2 Models: Llama2.md
      - Mistral Models: Mistral.md
      - MosaicMPT Models: MosaicMPT.md
      - PytorchServer: PyTorchServer.md
      - TrainingExample: TrainingExample.md
  - Linen:
      - Bits: linen-bits.md
      - Utils: linen-utils.md
  - Modules:
      - Auto Models: modules-auto_models.md
      - Falcon:
          - Falcon Configuration: modules-falcon-falcon_configuration.md
          - Modelling Falcon Flax: modules-falcon-modelling_falcon_flax.md
      - Flax Modelling Utils: modules-flax_modelling_utils.md
      - Gpt J:
          - Gpt J Configuration: modules-gpt_j-gpt_j_configuration.md
          - Modelling Gpt J Flax: modules-gpt_j-modelling_gpt_j_flax.md
      - Gpt Neo X:
          - Gpt Neo X Configuration: modules-gpt_neo_x-gpt_neo_x_configuration.md
          - Modelling Gpt Neo X Flax: modules-gpt_neo_x-modelling_gpt_neo_x_flax.md
      - Gpt2:
          - Gpt2 Configuration: modules-gpt2-gpt2_configuration.md
          - Modelling Gpt2 Flax: modules-gpt2-modelling_gpt2_flax.md
      - Llama:
          - Llama Configuration: modules-llama-llama_configuration.md
          - Modelling Llama Flax: modules-llama-modelling_llama_flax.md
      - Lucid Transformer:
          - Lt Configuration: modules-lucid_transformer-lt_configuration.md
          - Modelling Lt Flax: modules-lucid_transformer-modelling_lt_flax.md
      - Mistral:
          - Mistral Configuration: modules-mistral-mistral_configuration.md
          - Modelling Mistral Flax: modules-mistral-modelling_mistral_flax.md
      - Mixtral:
          - Mixtral Configuration: modules-mixtral-mixtral_configuration.md
          - Modelling Mixtral Flax: modules-mixtral-modelling_mixtral_flax.md
      - Mosaic Mpt:
          - Modelling Mpt Flax: modules-mosaic_mpt-modelling_mpt_flax.md
          - Mosaic Configuration: modules-mosaic_mpt-mosaic_configuration.md
      - Opt:
          - Modelling Opt Flax: modules-opt-modelling_opt_flax.md
          - Opt Configuration: modules-opt-opt_configuration.md
      - Palm:
          - Modelling Palm Flax: modules-palm-modelling_palm_flax.md
          - Palm Configuration: modules-palm-palm_configuration.md
      - Phi:
          - Modelling Phi Flax: modules-phi-modelling_phi_flax.md
          - Phi Configuration: modules-phi-phi_configuration.md
      - T5:
          - Modelling T5 Flax: modules-t5-modelling_t5_flax.md
          - T5 Configuration: modules-t5-t5_configuration.md
  - Partitioning:
      - Partitioner: partitioning-partitioner.md
  - Reinforcement Learning:
      - Core: reinforcement_learning-core.md
      - Models:
          - Modelling Base: reinforcement_learning-models-modelling_base.md
          - Modelling Value Head: reinforcement_learning-models-modelling_value_head.md
      - Trainer:
          - Base: reinforcement_learning-trainer-base.md
          - Ppo Config: reinforcement_learning-trainer-ppo_config.md
          - Ppo Trainer: reinforcement_learning-trainer-ppo_trainer.md
  - Serve:
      - Jax Serve: serve-jax_serve.md
      - Torch Serve: serve-torch_serve.md
      - Utils: serve-utils.md
  - Smi:
      - Smi: smi-smi.md
  - Trainer:
      - Causal Language Model Trainer: trainer-causal_language_model_trainer.md
      - Training Configurations: trainer-training_configurations.md
  - Transform:
      - Easydel Transform: transform-easydel_transform.md
      - Falcon: transform-falcon.md
      - Llama: transform-llama.md
      - Mistral: transform-mistral.md
      - Mpt: transform-mpt.md
      - Utils: transform-utils.md
  - Utils:
      - Checker: utils-checker.md
      - Prompters: utils-prompters.md
      - Tensor Utils: utils-tensor_utils.md
      - Utils: utils-utils.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx

repo_url: https://github.com/erfanzar/EasyDel
site_author: Erfan Zare Chavoshi
site_name: EasyDel

theme:
  highlightjs: true
  hljs_languages:
    - yaml
    - python
  name: material
