site_name: "EasyDel"

copyright: "Erfan Zare Chavoshi-EasyDel"

site_author: "Erfan Zare Chavoshi"
repo_url: "https://github.com/erfanzar/EasyDel"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx

theme:
  name: material
  highlightjs: true
  hljs_languages:
    - yaml
    - python

nav:
  - Home: index.md
  - Install: Install.md
  - AvailableModels: AvailableModels.md
  - EasyBIT: Bits.md
  - Eval:
      - lm_eval: lib-python-EasyDel-eval-lm_eval.md
  - Transform:
      - easydel_transform: lib-python-EasyDel-transform-easydel_transform.md
      - mpt: lib-python-EasyDel-transform-mpt.md
      - llama: lib-python-EasyDel-transform-llama.md
      - falcon: lib-python-EasyDel-transform-falcon.md
      - mistral: lib-python-EasyDel-transform-mistral.md
      - utils: lib-python-EasyDel-transform-utils.md
  - smi: lib-python-EasyDel-smi-smi.md
  - Serve:
      - torch_serve: lib-python-EasyDel-serve-torch_serve.md
      - jax_serve: lib-python-EasyDel-serve-jax_serve.md
      - utils: lib-python-EasyDel-serve-utils.md
  - Modules:
      - Falcon: lib-python-EasyDel-modules-falcon-modelling_falcon_flax.md
      - Palm: lib-python-EasyDel-modules-palm-modelling_palm_flax.md
      - flax_modelling_utils: lib-python-EasyDel-modules-flax_modelling_utils.md
      - GPT-Neox: lib-python-EasyDel-modules-gpt_neo_x-modelling_gpt_neo_x_flax.md
      - GPT-J: lib-python-EasyDel-modules-gpt_j-modelling_gpt_j_flax.md
      - Mistral: lib-python-EasyDel-modules-mistral-modelling_mistral_flax.md
      - auto_models: lib-python-EasyDel-modules-auto_models.md
      - LucidTransformers: lib-python-EasyDel-modules-lucid_transformer-modelling_lt_flax.md
      - OPT: lib-python-EasyDel-modules-opt-modelling_opt_flax.md
      - MPT: lib-python-EasyDel-modules-mosaic_mpt-modelling_mpt_flax.md
      - Llama: lib-python-EasyDel-modules-llama-modelling_llama_flax.md
      - Mixtral: lib-python-EasyDel-modules-mixtral-modelling_mixtral_flax.md
      - PHI: lib-python-EasyDel-modules-phi-modelling_phi_flax.md
      - T5: lib-python-EasyDel-modules-t5-modelling_t5_flax.md
  - configs: lib-python-EasyDel-configs-configs.md
  - Utils:
      - tensor_utils: lib-python-EasyDel-utils-tensor_utils.md
      - prompters: lib-python-EasyDel-utils-prompters.md
      - utils: lib-python-EasyDel-utils-utils.md
      - checker: lib-python-EasyDel-utils-checker.md
  - RLHF:
      - trainer: lib-python-EasyDel-rlhf-trainer.md
      - reward: lib-python-EasyDel-rlhf-reward.md
      - ppo: lib-python-EasyDel-rlhf-ppo.md
      - utils: lib-python-EasyDel-rlhf-utils.md

  - Trainer:
      - fsdp_train: lib-python-EasyDel-trainer-fsdp_train.md
      - config: lib-python-EasyDel-trainer-config.md
      - tf_dataset: lib-python-EasyDel-trainer-tf_dataset.md
      - training_utils: lib-python-EasyDel-trainer-training_utils.md
  - Linen:
      - bits: lib-python-EasyDel-linen-bits.md
      - utils: lib-python-EasyDel-linen-utils.md
  - RL Trainer:
      core: lib-python-EasyDel-reinforcement_learning-core.md
      models:
        modelling_base: lib-python-EasyDel-reinforcement_learning-models-modelling_base.md
        modelling_value_head: lib-python-EasyDel-reinforcement_learning-models-modelling_value_head.md
      trainer:
        base: lib-python-EasyDel-reinforcement_learning-trainer-base.md
        ppo_trainer: lib-python-EasyDel-reinforcement_learning-trainer-ppo_trainer.md
  - Data Preprocessing:
      - data_preprocessing/_processor: lib-python-EasyDel-data_preprocessing-_processor.md
  - Examples:
      - PytorchServer: PyTorchServer.md
      - JAXServer: JAXServer.md
      - DataProcessing: DataProcessing.md
      - TrainingExample: TrainingExample.md
      - Falcon Models: Falcon.md
      - Llama Models: Llama.md
      - Llama2 Models: Llama2.md
      - Mistral Models: Mistral.md
      - MosaicMPT Models: MosaicMPT.md


